version: '3'
services:
  geniesys:
    image: "irusri/docker4geniesys:latest"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "80:80"
      - "3002:3006"
    environment:
      - "MYSQL_ADMIN_PASS=mypass"
    volumes: 
      - "${PWD}/geniesys:/app/geniesys"  
      - "${PWD}/mysql:/var/lib/mysql"
